### ISSUE TITLE
Mod just doesn't work

### ISSUE THREAD

**Issue by justiziabelle** [forewing/payday2-ghost-mode#1]
Hi tried the mod for an easier time getting the vase achievement on "the ukrainian prisoner", but it doesn't work.
You still get detected by guards and civilians.
Got the achievement the old fashioned way anyways so no need for the mod anymore, still thought i'd let you know.

Payday 2 and Super BLT versions up to date 03/25/2023

**Comment by forewing** [comment]
Skill issue
________________________________
From: justiziabelle ***@***.***>
Sent: Saturday, March 25, 2023 2:18:19 PM
To: forewing/payday2-ghost-mode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [forewing/payday2-ghost-mode] Mod just doesn't work (Issue #1)


Hi tried the mod for an easier time getting the vase achievement on "the ukrainian prisoner", but it doesn't work.
Got the achievement the old fashioned way anyways so no need for the mod anymore, still thought i'd let you know.

Payday 2 and Super BLT versions up to date 03/25/2023
